"""initial tables

Revision ID: 8fc57c908caa
Revises: 
Create Date: 2026-02-13 02:57:23.446763
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8fc57c908caa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_compliance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pattern', sa.String(length=500), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_name')
    )
    op.create_table('kb_signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kb_tones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('kb_vips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_pattern', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_vips_email_pattern'), 'kb_vips', ['email_pattern'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('mailboxes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('credentials_ref', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailboxes_email_address'), 'mailboxes', ['email_address'], unique=True)
    op.create_table('email_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mailbox_id', sa.UUID(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('cc', sa.Text(), nullable=True),
    sa.Column('bcc', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_events_gmail_message_id'), 'email_events', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_email_events_thread_id'), 'email_events', ['thread_id'], unique=False)
    op.create_table('email_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_event_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('gmail_draft_id', sa.String(length=255), nullable=True),
    sa.Column('body_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'rejected', 'sent', name='draft_status'), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_event_id'], ['email_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_drafts_gmail_draft_id'), 'email_drafts', ['gmail_draft_id'], unique=False)
    op.create_table('approval_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('approved', 'rejected', 'edit_requested', name='approval_action_type'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('slack_message_ts', sa.String(length=100), nullable=True),
    sa.Column('slack_channel_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['email_drafts.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval_actions')
    op.drop_index(op.f('ix_email_drafts_gmail_draft_id'), table_name='email_drafts')
    op.drop_table('email_drafts')
    op.drop_index(op.f('ix_email_events_thread_id'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_gmail_message_id'), table_name='email_events')
    op.drop_table('email_events')
    op.drop_index(op.f('ix_mailboxes_email_address'), table_name='mailboxes')
    op.drop_table('mailboxes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_kb_vips_email_pattern'), table_name='kb_vips')
    op.drop_table('kb_vips')
    op.drop_table('kb_tones')
    op.drop_table('kb_signatures')
    op.drop_table('kb_compliance')
    # ### end Alembic commands ###
